# Generated by Django 6.0.4 on 2026-06-24 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_socios/', verbose_name='Foto Carnet')),
                ('plan_contratado', models.CharField(choices=[('MENSUAL', 'Mensual ($30.00)'), ('SEMESTRAL', 'Semestral ($150.00)'), ('ANUAL', 'Anual ($280.00)')], default='MENSUAL', max_length=15, verbose_name='Plan Contratado')),
                ('turno_preferido', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MANANA', max_length=10, verbose_name='Turno Preferido')),
                ('cuenta_con_casillero', models.BooleanField(default=False, verbose_name='¿Cuenta con casillero alquilado?')),
                ('fecha_inscripcion', models.DateField(verbose_name='Fecha de Inscripción')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_pdf', models.FileField(upload_to='certificados_medicos/', verbose_name='Certificado Médico (PDF)')),
                ('presion_arterial', models.CharField(max_length=20, verbose_name='Presión Arterial')),
                ('nivel_aptitud', models.CharField(choices=[('APTO', 'Apto para entrenar'), ('RESTRINGIDO', 'Restringido / No Apto')], default='APTO', max_length=15, verbose_name='Nivel de Aptitud')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de la Evaluación')),
                ('observaciones_medicas', models.TextField(blank=True, null=True, verbose_name='Observaciones Médicas')),
                ('socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='socios.socio', verbose_name='Socio')),
            ],
        ),
    ]
